### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by tchaler2017** [beranm14/siteBlock#1]
Hello sir, i am trying to the siteBlock but i am getting error. i am using kali linux 2017.3  64 bits. 
root@kali:~/siteBlock# python main.py
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    cd=Chdir("/user/share/contBlock")
  File "main.py", line 16, in __init__
    os.chdir(newPath)
Did i miss anything?? i even put the contBlock file to user/share/ directory but i am still getting the same error. thanks

**Comment by beranm14** [comment]
Yep, for some reasons I placed everything in `/usr/share/contBlock`. Who knows why, it has been a while I played with this repository. I've added some more detail in `README.md`.
